name: Test Execution and Publish Report

on:
  workflow_dispatch:
    inputs:
      parallel:
        type: boolean
        description: Run Tests in Parallel
        default: false

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  test-execution:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.6-eclipse-temurin-21

    steps:
      - name: Checkout the Repository to Runner
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: /root/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout Book API. Node.js App Repository
        uses: actions/checkout@v4
        with:
          repository: NayeemJohnY/book-nodejs-app  
          path: books-nodejs-app

      - name: Install dependencies
        run: 
          npm install --prefix books-nodejs-app

      - name: Start Book NodeJS App
        run: |
          npm run start-pm2 --prefix books-nodejs-app
          sleep 20

      - name: Execute Test
        run: |
          if [ "${{ github.event.inputs.parallel }}" = "true" ]; then
            mvn clean test -Dparallel=true
          else
            mvn clean test
          fi

      - name: Stop Book NodeJS App
        if: always()
        run: npm run stop-pm2 --prefix books-nodejs-app

      - name: Generate Allure Report
        if: success() || failure()
        uses: NayeemJohnY/actions/allure-report-with-history@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results

      - name: Build Maven Javadocs
        if: success() || failure()
        run: mvn javadoc:javadoc javadoc:test-javadoc

      - name: Prepare GitHub Pages Content
        if: success() || failure()
        uses: NayeemJohnY/actions/prepare-github-pages@main
        with:
         reports-dir: test-results/allure-report
         javadoc-dir: target/reports

      - name: Deploy GitHub Pages
        if: success() || failure()
        uses: NayeemJohnY/actions/deploy-github-pages-site@main
